#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/rtorrent,/log/rutorrent,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/downloads \
	/blackhole \
    /processing \
	/run/php

# configure ruTorrent
cd /defaults/rutorrent-conf || exit
shopt -s globstar nullglob
for i in *
do
	[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
done

# Configure ruTorrent plugins
cd /defaults/rutorrent-profiles || exit
shopt -s globstar nullglob
for i in *
do
	[[ ! -e "/config/rutorrent/profiles/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/profiles/settings/${i}"
done

# tell autotools to check for new torrents every minute.
sed -i 's/$autowatch_interval = 300;/$autowatch_interval = 60;/' /app/rutorrent/plugins/autotools/conf.php


# rtorrent configuration
[[ ! -e /config/rtorrent/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /config/rtorrent/rtorrent.rc
cp -pr /config/rutorrent/settings/* /app/rutorrent/conf/

# move and symlink themes folder for custom theme usage
[[ ! -e /config/themes ]] && \
	mv /app/rutorrent/plugins/theme/themes /config/
rm -rf /app/rutorrent/plugins/theme/themes
ln -s /config/themes /app/rutorrent/plugins/theme/themes

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

# permissions
chown -R abc:abc \
	/downloads \
	/blackhole \
	/processing


chown -R abc:abc \
	/config \
	/run \
	/app/rutorrent

chmod -R 755 /config/rutorrent/profiles
